= Enrichissement culturel

== Vie Universitaire 

L'école de technologie supérieur est un très grand institut qui accueille énormément d'étudiants étrangers à chaque  semestre.  Le  système  administratif  est  assez  bien  organisé,  je  n'ai  pas  vraiment  eu  de problème. 

Au niveau des cours, il faut savoir que les québécois peuvent choisir les cours qu'ils veulent suivre durant leur session parmi une liste de leur diplôme. En tant qu'étudiant étranger j'ai donc pu piocher  parmi  ce  qui  m'intéressait. Les cours sont composés à moitié d'heures magistrales et à moitié d'heure de travaux pratiques, ce qui se rapproche beaucoup de l'IUT ici en France. Il y a des examens à la mi-session et en fin de session ainsi que des TP ou des devoirs en fonction des cours. Le système de note est assez complexe (comme vu au chapitre 1). 

Les relations avec les professeurs sont plus souples qu'en France. Ils sont ouverts à toutes questions et disponible pour donner de l'aide. Certains se font même appeler par leur prénom. Les cours dans leur globalité sont assez trompeurs pour les étrangers car ils sont souvent très complets. On commence les premières semaines par des choses simples mais cela devient très vite pour complexe et il ne faut pas se laisser aller dès le début car c'est difficile de se rattraper par la suite.

== Vie quotidienne

Les   transports   en   commun   sont   très répandus   et   fréquents.   La   Société   de Transport  de  Montréal  (STM)  opère  165 lignes de bus et quatre lignes de métro sept jours sur sept. Il est possible de prendre des bus vingt-quatre heures sur vingt-quatre ; en revanche les métros s’arrêtent aux alentours de une heure du matin. [6] Les  magasins  sont  ouverts  tous  les  jours,  en général jusqu’à dix-neuf heures, jusqu’à seize heures  le  week-end.  Vous  trouverez  des "dépanneurs", petites épiceries, un peu partout ouvert vingt-quatre heures sur vingt-quatre mais pratiquant des prix plus élevés. Le centre ville regorge de grands centres commerciaux dont une partie est souterraine afin de les relier entre eux et au métro. 

Les constructions souterraines s’avèrent très pratiques pendant l’hiver, celui-ci  étant  assez  rude.  Il  est  rare  de  voir  des  températures  positives  entre décembre  et  mars.  La  météo  annonce  toujours  deux  températures :  la température réelle, et la température ressentie, qui est plus froide à cause du facteur  vent.  Ainsi,  -26°  peut  être  ressenti  comme -40°.
