= Enrichissement culturel

== Vie Universitaire 

L'école de technologie supérieur est un très grand institut qui accueille énormément d'étudiants étrangers à chaque  semestre. Le système  administratif  est  assez  bien  organisé, je n'ai pas vraiment eu de problème. 

Au niveau des cours, il faut savoir que les québécois peuvent choisir les cours qu'ils veulent suivre durant leur session parmi une liste de leur diplôme. En tant qu'étudiant étranger j'ai donc pu piocher  parmi  ce  qui  m'intéressait. Les cours sont composés à moitié d'heures magistrales et à moitié d'heure de travaux pratiques, ce qui se rapproche beaucoup de l'IUT ici en France. Il y a des examens à la mi-session et en fin de session ainsi que des TP ou des devoirs en fonction des cours. Le système de note est assez complexe (comme vu au chapitre 1). 

Les relations avec les professeurs sont plus souples qu'en France. Ils sont ouverts à toutes questions et disponible pour donner de l'aide. Certains se font même appeler par leur prénom. Les professeurs se sentent proches des élèves et il n’y a pas de cadre très formel. Tout le monde se tutoie mais il peut parfois être choquant pour nous étudiant français de voir un élève Québécois mécontent face à un professeur. Les cours dans leur globalité sont assez trompeurs pour les étrangers car ils sont souvent très complets. On commence les premières semaines par des choses simples mais cela devient très vite pour complexe et il ne faut pas se laisser aller dès le début car c'est difficile de se rattraper par la suite.

== Vie quotidienne

Le Québec est connu pour son hiver plutôt froid. Il faut s'y préparer car il dur une grande parti de l'année (novembre à avril environs). La  météo  annonce  toujours deux températures : la température réelle, et la température ressentie, qui est plus froide à cause du facteur vent. Ainsi, -26°  peut  être ressenti comme -40°. Mais une fois qu'on est équipé, la température n'est plus un problème. Et beaucoup d'activités sont proposées l'hiver, que ce soit pas l'université ou par la ville. 

Au niveau de leur rythme de vie, il ressemble dans l'ensemble à celui des français. La différence flagrante est au niveau du repas du soir. En effet, au Québec le souper se prend tout de suite après la fin du travail. Ainsi, les québécois mangent entre 17h et 18h généralement.

Les   transports en commun sont très répandus et fréquents. La Société de Transport de Montréal (STM) opère 165 lignes de bus et quatre lignes de métro sept jours sur sept. Il est possible de prendre des bus vingt-quatre heures sur vingt-quatre. En revanche les métros s’arrêtent aux alentours de une heure du matin. Les  magasins  sont  ouverts  tous les jours, en général jusqu’à dix-neuf heures, jusqu’à seize heures  le  week-end.  Vous  trouverez des "dépanneurs", petites épiceries, un peu partout ouvert vingt-quatre heures sur vingt-quatre mais pratiquant des prix plus élevés. Le centre ville regorge de grands centres commerciaux dont une partie est souterraine afin de les relier entre eux et au métro. 

Au niveau de la nourriture, on est en Amérique donc des concessions sont à faire sur certains points.  Mais  on  trouve  vite son compte. Il n’y a pas de grandes spécialités au-delà de la poutine et du sirop d’érable ou de plats à base de ce produit local mais en général on y mange bien. A savoir que les pharmacies ne vendent pas que des médicaments mais aussi des cosmétiques et de la nourriture. 

== Bilan personnel 

Je tire un bilan  très positif de mon année à l’étranger. En effet, il n’est pas très facile au début de se retrouver loin de sa famille ainsi que de ses amis. Néanmoins je ne tire que du positif de cette expérience, en effet, je suis devenu bien plus mature qu’auparavant et bien plus autonome. D'une manière général je dirais ce séjour à fait naitre en moi l'envie de voyager et de découvrir le monde. Je n'étais encore jamais parti aussi  loin et aussi longtemps de la France. J'ai  appris à me débrouiller par moi-même, à être un peu plus curieu de ce qui m'entour et à m'ouvrir aux autres. Ma vision de la vie à sans doute évolué au court des mois. Je ne rentre pas en France avec les mêmes envies et les mêmes attentes mais c'est une bonne chose. 
