= les démarches

//TODO

== Les cours

=== Première session

Lors de mon inscription à l'ETS, il m'a été proposé d'être inscrit automatiquement aux cours de base de début de formation. J'ai accepté cette proposition, et j'ai donc eu accès aux cours Log100 (informatique), Mat145 (mathématiques), Com100 (communication) et Chim131 (chimie). Tous ces cours, et plus généralement tout les cours de l'ETS fonctionnent d'une manière similaire de celle que j'ai pu expérimenter avec l'IUT de Bordeaux. La première moité du volume horaire d'un cours est purement théorique là ou la deuxième moitié est purement pratique.

En règle générale, la difficulté des cours pour cette première session est relativement simple. Le cours d'informatique correspondait au niveau de la première année de DUT informatique, vu en accéléré. La communication part elle aussi de zéros et ne requiert pas vraiment de connaissances préalables. Les mathématiques correspondent à un niveau lycée et ne sont pas des mathématiques informatiques. Ils sont donc à la portée de tous élève provenant de DUT. Pour mon cas, les mathématiques n'ont jamais était mon fort, j'ai cependant réussi à accrocher la moyenne.

J'ai cependant un avis partagé sur le cours de chimie : ce cours semble s'inscrire dans la continuité des études entrepris par les Québécois. Cependant pour nous, étudiants français, cela remonte à plusieurs années. De ce fait, et dû à mes lacunes dans cette matière, je n'ai pas réussi à valider ce cours.

=== Deuxième session

Pour cette session, je me suis inscrit moi-même aux cours et par ce fait, j'ai dû faire des choix. Les inscriptions aux cours se font pendant une courte période de la session. Le système d'inscriptions est donc saturé dès son ouverture, car la majorité des cours de l'ETS ont un nombre de places limité. Les places aux cours partent donc très vite.

Une partie des cours que j'avais prévu de suivre via mon contrat pédagogique étaient donc plein. J'ai essayé d'en choisir de nouveaux qui se rapprochent de ceux initialement choisis. J'ai donc dû remplacer ING150 par PHY144 "Introduction à la physique du génie". Mais aussi pendant un moment, LOG121 par MAT260. Pour ce dernier, j'ai fini par réussir à récupérer LOG121 "Conception orientée objet", cela deux semaines après le début des cours. Ce fut une erreur de ma part de vouloir à tout prix récupérer ce cours. J'ai en effet eu du mal à rattraper mon retard sur les projets.

En ce qui concerne les cours les deux autres cours prévus dans le contrat pédagogique. À savoir LOG240 "Tests et maintenance ", et MAT210 "Logique et mathématiques discrètes", ce sont des cours qui s'inscrivent bien dans la lignée du DUT informatique. LOG240 fait suite au dernier semestre de DUT. Quant à MAT210, il reprend et approfondie des notions aussi vues en DUT.

À la fin de ce semestre, j'ai validé : MAT210, LOG240 et PH144.

=== La validation des cours

La quasi-intégralité des cours de l'ETS se valide par un système de double palier. En effet, il ne suffit pas d'avoir juste la moyenne dans le cours pour valider celui-ci.

Tout d'abord, la moyenne général d'un éléve au cour ne doit pas forcément être la moitié (50 % ou 10/20) pour valider celui-ci. Certains professeurs, en fonction de la classe, vont faire monter ou descendre ce seuil. Si la classe est performante, il peut faire monter le seuil à 55 % voir même à 60 %. À l'inverse, si la classe semble en difficulté par rapport aux évaluations du professeur, il pourra faire reculer ce seuil à par exemple 45 %.

Qui plus est, la moyenne aux contrôles écrit est aussi à obtenir. En effet comme nous l'avons vu précédemment, la moyenne général d'un élève doit correspondre au seuil fixé par le professeur. Elle regroupe l'ensemble des notes aux devoirs écrits, mais aussi les notes de travaux pratiques et de projet. L'ETS exige donc que la moyenne de tout les examens écrit soit elle supérieur ou égal à 50 %.

Il y a cependant une exception à ce double palier. Ce sont les cours dits "hors programme". Ces cours-ci demandant d'obtenir une moyenne général de 60 % et rien d'autres.

== Le logement

=== La recherche

En général, les étudiants étrangers habitent en colocation, c'est pourquoi j'ai commencé par prospecter par ce type d'annonce. Connaissant plusieurs autres personnes qui partaient vivre à Montréal au même, j'ai fini par penser que cela serait chose aisé. En parallèle j'ai tout de même candidaté aux résidences étudiante de l'ETS.

La recherche la collocation a fini par prendre beaucoup de temps, sans pour autant mener à une solution. Et au mois de juillet, j'ai appris que j'avais accès aux résidences l'ETS. J'ai fini par choisir cette option pour clore ma phase de recherche de logement.

=== L'appartement

J’ai donc habité dans un appartement 5 1⁄2 qui équivaut un T5 en France au prix de 480 $ par mois (environ 320 €). L'appartement est situé à Griffintown et, est composé de 4 chambres, de deux salles de bain et d'une grande pièce principale composé d'un salon et de la cuisine. Il été situé à 2 min de l’ETS, ce qui est un grand plus. Le prix du loyer est relativement cher (4 étudiants qui payent ~500 $ soit ~2000 $ par mois) par rapport au prix des autres logements de cette superficie dans ce quartier. Une partie du prix se justifiant par la proximité de l’école. Ce qui permet de ne pas forcément payer un abonnement aux transports en commun, qui est relativement cher. Il n’y avait aucune caution a payé ni assurance à fournir, et les charges sont incluses dans le prix.

== Les Coûts

=== Avant le départ

Il faut savoir qu'une grosse partie des dépenses que j'ai effectuées dans cette année se trouvent avant mon départ. Parmi ces dépenses préalables au départ, il y a de nombreuses dépenses en ce qui concerne les frais de dossier : pour la demande de permis de travail, de permis d'études ou encore pour l'inscription à l'ETS. Pour chacun de ces dossiers, il faut compter en moyenne 40 euros par dossier.

Il faut savoir qu'une bonne partie de ces dossiers sont fait pour obtenir un permis d'étude et un permis de travail. Ce qui est important à savoir et que, peut importe les frais de dossier, l'obtention de ces permis exige une preuve de capacité financière plutôt énorme. J'ai en effet vu mes dossiers refusés une première fois, malgré un emprunt à la banque pour une solvabilité montant à 10 000 euros. En effet, le site de l'immigration du Canada réclame environ 10 000 euros de preuve pour obtenir des permis. Pour ma part, ma preuve montait à 10 000 environ. Mais puisque qu'elle ne les dépassait pas franchement, la demande a été refuse. Contraignant à de nouveau trouver des fonds, et à effectuer encore une demande. 

Concernant les permis, depuis juillet 2018, il faut maintenant fournir ses empreintes digitales pour obtenir ces derniers. Il faut donc compter un allé retour à Paris, car il n'y a qu'un seul bureau en France et il se trouve à Paris.

=== A Montréal

Premièrement, il faut faire attention avec sa carte de paiement. Il a évidemment des coûts liés aux frais à l’étranger lors de retraits ou de paiements par carte. Pour résoudre ce problème, je n’ai pas choisi d’ouvrir un compte sur place, en raison de la durée de mon séjour, mais plutôt de prendre une option pour ma carte adaptée à mon type de voyage auprès de ma banque.

La plus grande des contraintes que j’ai pu rencontrer concernant les paiements sur place est que bon nombre de magasins ou organisations n’accepte pas le paiement par carte de crédit, mais seulement par carte de débit. Par exemple, pour payer mon loyer, j’étais contraint de retirer les sous en espèces pour les donner au bureau des résidences sachant que les sommes s’élevaient à environ 500 $ le premier semestre, cela était loin d’être pratique.

En ce qui concerne la vie de tous les jours, le coût de la vie s'apparente au coût de la vie dans une grande ville française. Comme présenté un peu plus tôt, le logement est d'environ 320 euros par mois. À cela, il faut rajouter le prix de l'alimentation, qui était en ce qui me concerne cela me coûtait entre 20 et 35 euros par semaine, soit environ 100 euros par mois.

=== Santé

Dès mon inscription à l’ETS, je devais transmettre un formulaire rempli par la CPAM de Bordeaux indiquant les dates d’arrivée et de départ du Québec. Les démarches furent assez simples, car la France bénéficie d’ententes avec le Québec sur le régime de santé. Une fois arrivé à Montréal, j'ai pu obtenir ma carte me rattachant a la régie de l'assurance-maladie du Québec (RAMQ).

Grâce à cette entente, il suffit de payer son assurance-maladie en France, et l'on profite des services santé du Québec comme si l'on paierait l'assurance-maladie du Québec.

Je n'ai pas beaucoup plus d'informations à ce sujet, étant donné que je n'ai jamais été malade durant mon séjour. J'ai cependant pu noter que le dentiste n'est pas rattaché au régime de l'assurance-maladie. Les cabinets sont donc tenu par des entreprises privées, et le coût résultant est extrêmement cher comparé aux prix en France.

=== Télécommunications

La téléphonie au Canada est très peu développée, et le prix des services fournis est extrêmement élevé. Surtout en ce qui concerne le prix des données permettant l'accès à Internet. En moyenne 90 dollars pour appel et sms illimité plus un giga de données internet. J'ai donc choisi de ne pas souscrire à un forfait téléphonique. À savoir que Montréal est une ville qui dispose d'un très bon réseau de wifi publique. Grâce à cela, j'ai pu effectuer mes 8 mois sans trop de problèmes d'un point de vue télécommunication.
